package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallExpress;
import org.linlinjava.litemall.db.domain.LitemallExpressExample;

public interface LitemallExpressMapper {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    int insert(LitemallExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    int insertSelective(LitemallExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    LitemallExpress selectOneByExample(LitemallExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    LitemallExpress selectOneByExampleSelective(@Param("example") LitemallExpressExample example, @Param("selective") LitemallExpress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    List<LitemallExpress> selectByExampleSelective(@Param("example") LitemallExpressExample example, @Param("selective") LitemallExpress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    List<LitemallExpress> selectByExample(LitemallExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    LitemallExpress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallExpress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    LitemallExpress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    LitemallExpress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallExpress record, @Param("example") LitemallExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallExpress record, @Param("example") LitemallExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallExpress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}